name: instasafe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  crypto: ^3.0.6
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_isolate: ^2.0.4
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_mlkit_face_detection: ^0.13.1
  google_sign_in: ^6.1.5
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.1.0
  image: ^3.3.0
  image_picker: ^1.0.4
  intl: ^0.20.2
  logging: ^1.2.0
  synchronized: ^3.0.0
  tflite_flutter: ^0.10.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/modelos/mobilefacenet_ente_web.tflite
    - assets/image/
