name: instasafe
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.11.2                     
  crypto: ^3.0.6
  flutter_isolate: ^2.0.4
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  google_mlkit_face_detection: ^0.13.1
  google_sign_in: 6.3.0
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.4.0
  image_picker: ^1.0.4
  image: ^4.1.7
  intl: ^0.20.2
  logging: ^1.2.0
  ml_linalg: ^13.12.6
  synchronized: ^3.0.0          
  mobile_scanner: ^7.0.1
  vector_math: ^2.1.4
  tflite_flutter: ^0.11.0    

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/modelos/mobilefacenet_ente_web.tflite
    - assets/modelos/blazeface_back_ente_web.tflite
    - assets/modelos/blur_detection_model.tflite
    - assets/modelos/emotion_detection_model.tflite
    - assets/modelos/FaceAntiSpoofing.tflite
    - assets/image/logo_istasafe.png
